#params from adaprive clustering 
/cuda_cone_rush_node:
  ros__parameters:
    input_topic: /lidar_points #/lidar_points #/patchworkpp/nonground
    segmented_topic: /segmented_points
    filtered_topic: /filtered_points
    cluster_topic: /clusters #/perception/newclusters
    frame_id: "hesai_lidar"

    #clustering
    minClusterSize : 1        # Minimum cluster size to filter out noise
    maxClusterSize : 500      # Maximum size for large objects
    voxelX: 0.8               # Down-sampling resolution in X (meters)
    voxelY: 0.8               # Down-sampling resolution in Y (meters)
    voxelZ: 0.8               # Down-sampling resolution in Z (meters)
    countThreshold: 5         # Minimum points per voxel

    #filter for clusters
    clusterMaxX: 0.4
    clusterMaxY: 0.4
    clusterMaxZ: 0.4
    clusterMinX: -0.1
    clusterMinY: -0.1
    clusterMinZ: 0.1
    maxHeight: 0.4          # of the lowest point

    #filter
    downFilterLimitX: -25.0
    upFilterLimitX: 25.0
    downFilterLimitY: -25.0
    upFilterLimitY: 25.0
    downFilterLimitZ: -5.0
    upFilterLimitZ: 5.0

    #segmentation
    distanceThreshold: 0.1            # from the plane
    maxSegmentationDistance: 20.0        # how far the random points can be from the car to be considered for plane fitting (in meters)
    maxIterations: 80                 # by requiring the plane to be found form 3 points close to the car the max number of iterations can be reduce to 1/3
    probability: 0.75

    #options
    filter: true
    publishFilteredPc: false
    
    segment: true
    publishSegmentedPc: false
    
    clustering: true
    publishCluster: true

    limitWarning_ms: 30

    nsight_max_iterations: 200000
    
    

