#params from adaprive clustering 
/cuda_cone_rush_node:
  ros__parameters:
    # ================ Topics and Frames =================
    input_topic: /lidar_points
    segmented_topic: /segmented_points
    filtered_topic: /filtered_points
    cluster_topic: /clusters
    frame_id: "hesai_lidar"

    # ================ BARQ options =================
    BARQ_enabled: false      # Switch to BARQ to receive data (false to disable BARQ and use ROS2 as normal)
    BARQ_topic: /lidar_points
    BARQ_retry_delay_ms: 100
    BARQ_max_retries: 50
    BARQ_polling_rate_ms: 1  # ~1KHz

    # ================ Pipeline options =================
    ring_pipeline: false    # Work In Progress
    filter: true
    segment: true
    clustering: true
    
    publishFilteredPc: true
    publishSegmentedPc: true
    publishCluster: true

    # ================ Debug options =================
    limitWarning_ms: 30
    nsight_max_iterations: 20
    
    # ================ Filtering XYZ options =================
    downFilterLimitX: -25.0
    upFilterLimitX: 25.0
    downFilterLimitY: -25.0
    upFilterLimitY: 25.0
    downFilterLimitZ: -5.0
    upFilterLimitZ: 5.0

    # ================ Segmentation options =================
    distanceThreshold: 0.1            # from the plane
    maxSegmentationDistance: 2000.0        # how far the random points can be from the car to be considered for plane fitting (in meters)
    maxIterations: 80                 # by requiring the plane to be found form 3 points close to the car the max number of iterations can be reduce to 1/3
    probability: 0.75
    
    # ================ Clustering options =================
    minClusterSize : 1        # Minimum cluster size to filter out noise
    maxClusterSize : 500      # Maximum size for large objects
    voxelX: 0.8               # Down-sampling resolution in X (meters)
    voxelY: 0.8               # Down-sampling resolution in Y (meters)
    voxelZ: 0.8               # Down-sampling resolution in Z (meters)
    countThreshold: 5         # Minimum points per voxel
    
    clusterMaxX: 0.4
    clusterMaxY: 0.4
    clusterMaxZ: 0.4
    clusterMinX: -0.1
    clusterMinY: -0.1
    clusterMinZ: 0.1
    maxHeight: 0.4          # of the lowest point
    
